version: '3'

services:
  log_assignment:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - log_network
    volumes:
      - logs_vw:/home/appuser/app/
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx_proxy:
    image: nginx
    networks:
      - log_network
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - log_assignment
    deploy:
      replicas: 1

networks:
  log_network:
    driver: bridge

volumes:
  logs_vw:
